# Copyright Adam B Kaplan
#
# SPDX-License-Identifier: CC-BY-4.0

title = "adambkaplan"
baseURL = "https://adambkaplan.com"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 9 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "adambkaplan"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = ""
author = "Adam B Kaplan"
favicon = "images/icons/favicon.ico"
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin",
  "mastodon",
  "bluesky"
]


[params.ananke.social.linkedin]
username = "adambkaplan"

[params.ananke.social.bluesky]
username = "adambkaplan"
profilelink = "https://bsky.app/profile/adambkaplan.bsky.social"

[params.ananke.social.mastodon]
username = "adambkaplan"
profilelink = "https://hachyderm.io/@adambkaplan"
