# Copyright Adam B Kaplan
#
# SPDX-License-Identifier: CC-BY-4.0

title = "adambkaplan"
baseURL = "https://adambkaplan.com"
languageCode = "en-us"
theme = "ananke"
copyright = "Adam B Kaplan"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/icons/favicon.ico"
  description = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-silver"
  featured_image = "/images/mouna_loa_sunset.JPG"

  [[params.ananke_socials]]
    name = "linkedin"
    url = "https://linkedin.com/in/adambkaplan"
    verify = true

  [[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/adambkaplan"
    verify = true

  [[params.ananke_socials]]
    name = "mastodon"
    url = "https://hachyderm.io/@adambkaplan"
    verify = true

  [[params.ananke_socials]]
    name = "github"
    url = "https://github.com/adambkaplan"
    verify = true
