title = "adambkaplan"
baseURL = "http://adambkaplan.com/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon_ico = "images/icons/favicon.ico"
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  linkedin = "https://linkedin.com/in/adambkaplan"
  github = "https://github.com/adambkaplan"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-silver"
  featured_image = "/images/mouna_loa_sunset.JPG"
  mainSections = "posts"
